### PR TITLE
Add link to AUR package

### PR DESCRIPTION
**Pull request by perry-mitchell**
Add ref in readme to AUR package.

### CODE REVIEW

**Comment by Defman21** [comment]
AUR package has boot 32 and 64 bit versions.

**Comment by perry-mitchell** [comment]
@Defman21 @sum01 Good call. I don't necessary like the idea of supporting 32bit platforms anymore, but if it's available then fine.

**Comment by sum01** [comment]
@perry-mitchell heh, I can remove the 32-bit stuff from the AUR if you want

**Comment by perry-mitchell** [comment]
> I can remove the 32-bit stuff from the AUR if you want

Perhaps it's more work to remove it than it is to update the readme 😅 - Thanks for the offer. Great that we've got yet another supported platform! 🙏

**Pull request merged**
