### PR TITLE
Nextcloud Support

### LINKED ISSUE #205: Nextcloud archive access
Similar to https://github.com/buttercup/buttercup/issues/39, it should be easy to add since Nextcloud is a community-driven fork of OwnCloud and we use WebDAV too. :)

See more info at https://github.com/nextcloud

### PR DESCRIPTION
**Pull request by sallar**
Fixes #205

### CODE REVIEW

**Comment by perry-mitchell** [comment]
@sallar Did you get nextcloud working alright?

**Comment by sallar** [comment]
@perry-mitchell no... the archive's being created but on reading "buttercup.min.js" returns 503... we have to check this together.

**Comment by perry-mitchell** [comment]
Any-fs 0.3.0 is out @sallar

**Comment by perry-mitchell** [comment]
Hi @jancborchardt - We're trying to get Nextcloud working, but there seems to be a 503 error coming when requesting the archive **after** we've created it (via WebDAV PUT). Accessing it later with GET works, but when trying GET immediately we get a 503 Service unavailable error. We don't see the same with ownCloud, though it's hosted in my house and not remotely (as such) like the Nextcloud demo we're using.

Any ideas?

**Comment by jancborchardt** [comment]
@perry-mitchell sorry for the late reply! Can you help here @morrisjobke @icewind1991 @rullzer?

**Comment by rullzer** [comment]
Uhm it is hard to judge. Probably something goes wrong.

What does the network log show?

**Comment by perry-mitchell** [comment]
@sallar Let's have another look at this tomorrow so we can get some info back to the Nextcloud gents.

@rullzer @jancborchardt It seems that there is, imo, some lag when creating a file via PUT. We create a new archive, PUT it to Nextcloud WebDAV, and then try to retrieve it immediately after that operation has finished - the resulting 503 makes it feel like Nextcloud hasn't finished writing the file, or it is delayed or not yet ready for consumption.

Is there some difference between ownCloud + Nextcloud in how files are written to the database? Could the Nextcloud demo installations be any different to an average Nextcloud installation in terms of database / speed / asynchronicity?

**Comment by perry-mitchell** [comment]
@sallar After trying this again in the core, I can't get the error occurring again. Using the following code, I get correct responses all the time:

```javascript
const Buttercup = require("buttercup");
const { Archive, NextcloudDatasource, createCredentials } = Buttercup;

let archive = Archive.createWithDefaults();
let nccreds = createCredentials("nextcloud");
nccreds.setValue("username", "admin");
nccreds.setValue("password", "perrym");
let ncds = new NextcloudDatasource(
    "https://demo.nextcloud.com/perrym/",
    "/test4.bcup",
    nccreds
);

ncds.save(archive, createCredentials.fromPassword("testing"))
    .then(function() {
        console.log("Saved");
        return ncds.load(createCredentials.fromPassword("testing"))
            .then(function(archive) {
                console.log("Good", archive.toObject());
            });
    })
    .catch(function(err) {
        console.error(err);
    });
```

image

**Comment by rullzer** [comment]
If the first put succeeds it is all done. We don't return until all is written properly.

But good it works now.

**Comment by sallar** [comment]
@jancborchardt @rullzer @perry-mitchell Nextcloud Support is added and is going out tonight in v0.17.0 :) Thanks for the help guys!

image

**Comment by jancborchardt** [comment]
Awesome! Thank you @sallar @perry-mitchell! :) Let us know when you have an announcement tweet or so, we can retweet that. cc @jospoortvliet

**Pull request merged**
