### PR TITLE
Add LastPass import option

### PR DESCRIPTION
**Pull request by lukechilds**
Just enables the LastPass options from here: https://github.com/buttercup/buttercup-importer/pull/12

Should probably wait until a new version of `buttercup-importer` is published with https://github.com/buttercup/buttercup-importer/pull/12 so I can bump the `buttercup-importer` version in `package.json` before merging this.

### CODE REVIEW

**Comment by perry-mitchell** [comment]
Importer version should be v0.9.0 for lastpass support.

**Comment by lukechilds** [comment]
Done 👍 

Tested this on my LastPass account with 254 entries and they seemed to have all migrated ok 🎉

**Comment by lukechilds** [comment]
@sallar No probs 👍 

There is tiny bug I spotted in the LastPass importer so it might be best to get https://github.com/buttercup/buttercup-importer/pull/13 merged before merging this.

**Comment by perry-mitchell** [comment]
I'll merge this in a sec 👍

**Pull request merged**
